Repository Mechuleeare/Meturial-Server, pull requests merged in 2023-09, with the labels that each got.

#6 🔀 :: (#5) 모든 엔티티 생성 및 기본적인 프로젝트 세팅
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/todo.yaml
  .github/workflows/CI.yml
  build.gradle
  src/main/java/com/meturial/domain/.gitkeep
  src/main/java/com/meturial/domain/menu/domain/Menu.java
  src/main/java/com/meturial/domain/menu/domain/repository/MenuRepository.java
  src/main/java/com/meturial/domain/menu/domain/type/MenuType.java
  src/main/java/com/meturial/domain/notification/domain/MenuNotification.java
  src/main/java/com/meturial/domain/notification/domain/repository/MenuNotificationRepository.java
  src/main/java/com/meturial/domain/recipe/domain/ChoiceRecipe.java
  src/main/java/com/meturial/domain/recipe/domain/Recipe.java
  src/main/java/com/meturial/domain/recipe/domain/RecipeSequence.java
  src/main/java/com/meturial/domain/recipe/domain/repository/ChoiceRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/RecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/RecipeSequenceRepository.java
  src/main/java/com/meturial/domain/review/domain/Review.java
  src/main/java/com/meturial/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/meturial/domain/user/domain/User.java
  src/main/java/com/meturial/domain/user/domain/repository/UserRepository.java
  src/main/java/com/meturial/global/entity/BaseUUIDEntity.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/meturial/MeturialBackendApplicationTests.java
Labels: 프로젝트 세팅, 기능 추가

#8 🔀 :: (#7) Token 생성
  build.gradle
  src/main/java/com/meturial/MeturialBackendApplication.java
  src/main/java/com/meturial/domain/auth/domain/RefreshToken.java
  src/main/java/com/meturial/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/com/meturial/domain/user/domain/repository/UserRepository.java
  src/main/java/com/meturial/domain/user/exception/UserNotFoundException.java
  src/main/java/com/meturial/global/config/FilterConfig.java
  src/main/java/com/meturial/global/config/SecurityConfig.java
  src/main/java/com/meturial/global/error/ErrorCode.java
  src/main/java/com/meturial/global/exception/ExpiredJwtException.java
  src/main/java/com/meturial/global/exception/InvalidJwtException.java
  src/main/java/com/meturial/global/property/PropertyConfig.java
  src/main/java/com/meturial/global/redis/RedisConfig.java
  src/main/java/com/meturial/global/security/auth/AuthDetails.java
  src/main/java/com/meturial/global/security/auth/AuthDetailsService.java
  src/main/java/com/meturial/global/security/jwt/JwtProperty.java
  src/main/java/com/meturial/global/security/jwt/JwtTokenFilter.java
  src/main/java/com/meturial/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: 기능 추가

#10 🔀:: (#9) FCM 세팅
  .gitignore
  build.gradle
  src/main/java/com/meturial/infra/fcm/FcmConfig.java
  src/main/resources/application.yml
Labels: 프로젝트 세팅

#12 🔀 :: (#11) 이메일 인증 및 회원가입
  .gitignore
  build.gradle
  src/main/java/com/meturial/domain/auth/domain/Certification.java
  src/main/java/com/meturial/domain/auth/domain/repository/CertificationRepository.java
  src/main/java/com/meturial/domain/auth/domain/type/Certified.java
  src/main/java/com/meturial/domain/auth/exception/CodeAlreadyExpiredException.java
  src/main/java/com/meturial/domain/auth/exception/CodeNotCorrectException.java
  src/main/java/com/meturial/domain/auth/exception/EmailNotCertifiedException.java
  src/main/java/com/meturial/domain/auth/exception/SendMessageFailedException.java
  src/main/java/com/meturial/domain/auth/presentation/dto/request/EmailVerifiedRequest.java
  src/main/java/com/meturial/domain/auth/service/MailService.java
  src/main/java/com/meturial/domain/user/domain/User.java
  src/main/java/com/meturial/domain/user/exception/UserExistException.java
  src/main/java/com/meturial/domain/user/presentation/UserController.java
  src/main/java/com/meturial/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/meturial/domain/user/service/UserService.java
  src/main/java/com/meturial/global/entity/BaseUUIDEntity.java
  src/main/java/com/meturial/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: 기능 추가

#16 🔀 :: (#15) 로그인 기능 구현
  src/main/java/com/meturial/domain/auth/exception/UnAuthorizedException.java
  src/main/java/com/meturial/domain/auth/presentation/AuthController.java
  src/main/java/com/meturial/domain/auth/presentation/dto/request/UserSignInRequest.java
  src/main/java/com/meturial/domain/auth/presentation/dto/response/TokenResponse.java
  src/main/java/com/meturial/domain/auth/service/AuthService.java
  src/main/java/com/meturial/domain/user/service/UserService.java
  src/main/java/com/meturial/global/error/ErrorCode.java
  src/main/java/com/meturial/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#14 🔀 :: (#13) 식단 엔티티 구조 변경
  src/main/java/com/meturial/domain/menu/domain/Menu.java
  src/main/java/com/meturial/domain/notification/domain/MenuNotification.java
  src/main/java/com/meturial/domain/notification/domain/repository/MenuNotificationRepository.java
Labels: 구조 변경

#18 🔀 :: (#17) 유저 엔티티 알레르기정보 컬럼 추가
  src/main/java/com/meturial/domain/auth/domain/Certification.java
  src/main/java/com/meturial/domain/user/domain/User.java
  src/main/java/com/meturial/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/meturial/domain/user/service/UserService.java
Labels: 기능 추가

#21 🔀 :: (#20) 마이페이지 조회 기능 구현
  src/main/java/com/meturial/domain/user/presentation/UserController.java
  src/main/java/com/meturial/domain/user/presentation/dto/response/QueryMyInfoResponse.java
  src/main/java/com/meturial/domain/user/service/UserService.java
  src/main/java/com/meturial/global/security/SecurityFacade.java
  src/main/java/com/meturial/global/security/auth/AuthDetailsService.java
Labels: 기능 추가

#22 🔀 :: (#19) 로그아웃 기능 구현
  src/main/java/com/meturial/domain/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/com/meturial/domain/auth/presentation/AuthController.java
  src/main/java/com/meturial/domain/auth/service/AuthService.java
  src/main/java/com/meturial/global/error/ErrorCode.java
Labels: 기능 추가

#24 🔀 :: (#23) Modify mypage
  build.gradle
  src/main/java/com/meturial/domain/user/domain/User.java
  src/main/java/com/meturial/domain/user/presentation/UserController.java
  src/main/java/com/meturial/domain/user/presentation/dto/request/ModifyMypageRequest.java
  src/main/java/com/meturial/domain/user/service/UserService.java
  src/main/java/com/meturial/global/config/SecurityConfig.java
  src/main/java/com/meturial/global/security/jwt/JwtProperty.java
  src/main/resources/application.yml
Labels: 기능 추가

#26 💡 :: (#25) Email 로직 수정
  src/main/java/com/meturial/domain/auth/presentation/dto/request/SendEmailRequest.java
  src/main/java/com/meturial/domain/user/presentation/UserController.java
  src/main/java/com/meturial/domain/user/service/UserService.java
Labels: 기능 추가, 기능 수정

#28 🔀 :: (#27) 코드 수정
  src/main/java/com/meturial/domain/user/presentation/UserController.java
Labels: 기능 수정
