Repository Mechuleeare/Meturial-Server, pull requests merged in 2023-10, with the labels that each got.

#32 🔀 :: (#31) 토큰 재발급 기능 구현
  src/main/java/com/meturial/domain/auth/domain/RefreshToken.java
  src/main/java/com/meturial/domain/auth/presentation/AuthController.java
  src/main/java/com/meturial/domain/auth/service/AuthService.java
  src/main/java/com/meturial/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가, 기능 수정

#34 🔀 :: (#33) ERD 수정에 따른 엔티티 수정
  src/main/java/com/meturial/domain/recipe/domain/Recipe.java
  src/main/java/com/meturial/domain/recipe/domain/RecipeSequence.java
Labels: 구조 변경

#38 🔀 :: (#37) Review 엔티티 생성 시간 칼럼 추가
  src/main/java/com/meturial/domain/review/domain/Review.java
Labels: 구조 변경

#36 🔀 :: (#35) Dockerfile 추가
  .github/workflows/CD.yml
  Dockerfile
  build.gradle
Labels: 기능 추가

#40 🔀 :: (#39) Redis Config 및 Jwt 수정
  src/main/java/com/meturial/global/redis/RedisConfig.java
  src/main/java/com/meturial/global/security/jwt/JwtProperty.java
  src/main/java/com/meturial/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: 기능 수정, 구조 변경

#42 🔀 :: (#41) 찜 추가 기능 구현
  src/main/java/com/meturial/domain/recipe/domain/repository/ChoiceRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/RecipeRepository.java
  src/main/java/com/meturial/domain/recipe/exception/ChoiceRecipeExistException.java
  src/main/java/com/meturial/domain/recipe/exception/RecipeNotFoundException.java
  src/main/java/com/meturial/domain/recipe/facade/ChoiceRecipeFacade.java
  src/main/java/com/meturial/domain/recipe/facade/RecipeFacade.java
  src/main/java/com/meturial/domain/recipe/presentation/ChoiceRecipeController.java
  src/main/java/com/meturial/domain/recipe/service/ChoiceRecipeService.java
  src/main/java/com/meturial/global/error/ErrorCode.java
Labels: 기능 추가

#44 🔀 :: (#43) 찜 취소 API
  src/main/java/com/meturial/domain/recipe/domain/ChoiceRecipe.java
  src/main/java/com/meturial/domain/recipe/exception/ChoiceRecipeIsNotMineException.java
  src/main/java/com/meturial/domain/recipe/exception/ChoiceRecipeNotFoundException.java
  src/main/java/com/meturial/domain/recipe/facade/ChoiceRecipeFacade.java
  src/main/java/com/meturial/domain/recipe/facade/RecipeFacade.java
  src/main/java/com/meturial/domain/recipe/presentation/ChoiceRecipeController.java
  src/main/java/com/meturial/domain/recipe/service/ChoiceRecipeService.java
  src/main/java/com/meturial/global/error/ErrorCode.java
  src/main/java/com/meturial/global/security/SecurityFacade.java
Labels: 기능 추가

#46 🔀 :: (#45) Querydsl 설정
  build.gradle
  src/main/java/com/meturial/global/config/QuerydslConfig.java
  src/main/java/com/meturial/global/entity/BaseUUIDEntity.java
Labels: 프로젝트 세팅

#48 🔀 :: (#47) 레시피 상세 조회 API
  .gitignore
  src/main/java/com/meturial/domain/recipe/domain/Recipe.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeSequenceRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeSequenceRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/domain/repository/RecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/RecipeSequenceRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/vo/QueryRecipeDetailVo.java
  src/main/java/com/meturial/domain/recipe/exception/RecipeSequenceNotFoundException.java
  src/main/java/com/meturial/domain/recipe/presentation/RecipeController.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/QueryRecipeDetailResponse.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/RecipeSequenceElement.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
  src/main/java/com/meturial/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/meturial/global/error/ErrorCode.java
Labels: 기능 추가

#51 🔀 :: (#50) S3 설정
  build.gradle
  src/main/java/com/meturial/domain/image/presentation/ImageController.java
  src/main/java/com/meturial/domain/image/presentation/dto/response/ImageUrlResponse.java
  src/main/java/com/meturial/domain/image/service/ImageUploadService.java
  src/main/java/com/meturial/global/error/ErrorCode.java
  src/main/java/com/meturial/global/exception/SaveImageFailedException.java
  src/main/java/com/meturial/infra/s3/S3Config.java
  src/main/java/com/meturial/infra/s3/S3Facade.java
  src/main/resources/application.yml
Labels: 프로젝트 세팅, 기능 추가

#53 🔀 :: (#52) 찜한 레시피 목록 조회 기능 구현
  src/main/java/com/meturial/domain/recipe/domain/repository/ChoiceRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomChoiceRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomChoiceRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/domain/repository/vo/QueryChoiceRecipeListVo.java
  src/main/java/com/meturial/domain/recipe/presentation/ChoiceRecipeController.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/QueryChoiceRecipeListResponse.java
  src/main/java/com/meturial/domain/recipe/service/ChoiceRecipeService.java
Labels: 기능 추가
