Repository Mechuleeare/Meturial-Server, pull requests merged in 2023-11, with the labels that each got.

#56 🔀 :: (#55) ERD 변경에 따른 엔티티 자잘한 수정
  src/main/java/com/meturial/MeturialBackendApplication.java
  src/main/java/com/meturial/domain/recipe/domain/Recipe.java
  src/main/java/com/meturial/domain/recipe/domain/RecipeSequence.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/domain/repository/vo/QueryRecipeDetailVo.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
  src/main/java/com/meturial/global/entity/BaseUUIDEntity.java
  src/main/resources/application.yml
Labels: 구조 변경

#59 🔀 ::(#57) 평점 및 후기 삭제 API
  src/main/java/com/meturial/domain/recipe/service/ChoiceRecipeService.java
  src/main/java/com/meturial/domain/review/domain/Review.java
  src/main/java/com/meturial/domain/review/exception/ReviewIsNotMineException.java
  src/main/java/com/meturial/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/meturial/domain/review/presentation/ReviewController.java
  src/main/java/com/meturial/domain/review/service/ReviewService.java
  src/main/java/com/meturial/global/error/ErrorCode.java
Labels: 기능 추가

#61 🔀 :: (#60) 평점 및 후기 작성 API
  src/main/java/com/meturial/domain/recipe/presentation/ChoiceRecipeController.java
  src/main/java/com/meturial/domain/recipe/presentation/RecipeController.java
  src/main/java/com/meturial/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/meturial/domain/review/exception/ReviewExistException.java
  src/main/java/com/meturial/domain/review/presentation/ReviewController.java
  src/main/java/com/meturial/domain/review/presentation/dto/request/CreateReviewRequest.java
  src/main/java/com/meturial/domain/review/service/ReviewService.java
  src/main/java/com/meturial/global/error/ErrorCode.java
Labels: 기능 추가

#64 🔀 :: (#63) 레시피 상세 조회 API 오류 해결 및 조리 방법 정렬 코드 추가
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeSequenceRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeSequenceRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
  src/main/java/com/meturial/domain/review/service/ReviewService.java
Labels: 버그, 기능 추가

#69 🔀 :: (#68) CORS 설정
  src/main/java/com/meturial/global/config/CorsConfig.java
Labels: 프로젝트 세팅

#67 🔀 :: (#66) 레시피 별 후기 목록 조회 API
  src/main/java/com/meturial/domain/review/domain/Review.java
  src/main/java/com/meturial/domain/review/domain/repository/CustomReviewRepository.java
  src/main/java/com/meturial/domain/review/domain/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/meturial/domain/review/presentation/ReviewController.java
  src/main/java/com/meturial/domain/review/presentation/dto/response/QueryReviewListResponse.java
  src/main/java/com/meturial/domain/review/presentation/dto/response/ReviewElement.java
  src/main/java/com/meturial/domain/review/service/ReviewService.java
Labels: 기능 추가

#71 🔀 :: (#70) 내가 작성한 후기 목록 조회 API
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomChoiceRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/review/domain/repository/CustomReviewRepository.java
  src/main/java/com/meturial/domain/review/domain/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/meturial/domain/review/presentation/ReviewController.java
  src/main/java/com/meturial/domain/review/presentation/dto/response/MyReviewElement.java
  src/main/java/com/meturial/domain/review/presentation/dto/response/QueryMyReviewListResponse.java
  src/main/java/com/meturial/domain/review/service/ReviewService.java
Labels: 기능 추가, 기능 수정

#72 🔀 :: (#58) 평점 및 후기 수정 API
  src/main/java/com/meturial/domain/review/domain/Review.java
  src/main/java/com/meturial/domain/review/presentation/ReviewController.java
  src/main/java/com/meturial/domain/review/presentation/dto/request/UpdateReviewRequest.java
  src/main/java/com/meturial/domain/review/service/ReviewService.java
Labels: 기능 추가

#75 🔀 :: (#74) 메뉴 엔티티 User 엔티티랑 매핑 코드 추가
  src/main/java/com/meturial/domain/menu/domain/Menu.java
Labels: 구조 변경

#79 🔀 :: (#73) 식단 수정 API
  src/main/java/com/meturial/domain/menu/domain/Menu.java
  src/main/java/com/meturial/domain/menu/exception/MenuExistException.java
  src/main/java/com/meturial/domain/menu/exception/MenuIsNotMineException.java
  src/main/java/com/meturial/domain/menu/exception/MenuNotFoundException.java
  src/main/java/com/meturial/domain/menu/presentation/MenuController.java
  src/main/java/com/meturial/domain/menu/presentation/dto/request/UpdateMenuRequest.java
  src/main/java/com/meturial/domain/menu/service/MenuService.java
  src/main/java/com/meturial/global/error/ErrorCode.java
Labels: 기능 추가

#82 🔀 :: (#81) CD 서버에 배포 과정 추가
  .github/workflows/CD.yml
Labels: 기능 추가

#80 🔀 :: (#78) 특정 날짜 알람 설정 여부 조회 API
  src/main/java/com/meturial/domain/menu/domain/repository/CustomMenuRepository.java
  src/main/java/com/meturial/domain/menu/domain/repository/CustomMenuRepositoryImpl.java
  src/main/java/com/meturial/domain/menu/domain/repository/MenuRepository.java
  src/main/java/com/meturial/domain/notification/presentation/NotificationController.java
  src/main/java/com/meturial/domain/notification/presentation/dto/response/NotificationSettingElement.java
  src/main/java/com/meturial/domain/notification/presentation/dto/response/QueryNotificationSettingListResponse.java
  src/main/java/com/meturial/domain/notification/service/NotificationService.java
Labels: 기능 추가

#87 🔀 :: (#84) 식단 삭제 API
  src/main/java/com/meturial/domain/menu/presentation/MenuController.java
  src/main/java/com/meturial/domain/menu/service/MenuService.java
Labels: 기능 추가

#89 🔀 :: (#77) 특정 날짜 식단마다 알림 여부 설정 API
  src/main/java/com/meturial/domain/menu/domain/Menu.java
  src/main/java/com/meturial/domain/notification/presentation/NotificationController.java
  src/main/java/com/meturial/domain/notification/presentation/dto/request/UpdateNotificationSettingRequest.java
  src/main/java/com/meturial/domain/notification/service/NotificationService.java
Labels: 기능 추가

#90 🔀 :: (#85) 식단 상세 조회 API
  src/main/java/com/meturial/domain/menu/domain/Menu.java
  src/main/java/com/meturial/domain/menu/presentation/MenuController.java
  src/main/java/com/meturial/domain/menu/presentation/dto/request/UpdateMenuRequest.java
  src/main/java/com/meturial/domain/menu/presentation/dto/response/MenuDetailElement.java
  src/main/java/com/meturial/domain/menu/presentation/dto/response/QueryMenuDetailResponse.java
  src/main/java/com/meturial/domain/menu/service/MenuService.java
  src/main/java/com/meturial/domain/review/service/ReviewService.java
Labels: 기능 추가, 기능 수정

#91 🔀 :: (#76) 식단 목록 조회 API
  src/main/java/com/meturial/domain/menu/domain/repository/CustomMenuRepository.java
  src/main/java/com/meturial/domain/menu/domain/repository/CustomMenuRepositoryImpl.java
  src/main/java/com/meturial/domain/menu/presentation/MenuController.java
  src/main/java/com/meturial/domain/menu/presentation/dto/response/MenuNotificationElement.java
  src/main/java/com/meturial/domain/menu/presentation/dto/response/QueryMenuListResponse.java
  src/main/java/com/meturial/domain/menu/service/MenuService.java
Labels: 기능 추가

#92 🔀 :: (#88) 모든 카테고리 API
  src/main/java/com/meturial/domain/recipe/domain/Category.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CategoryRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomChoiceRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/presentation/RecipeController.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/CategoryElement.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/QueryCategoryResponse.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/QueryChoiceRecipeListResponse.java
  src/main/java/com/meturial/domain/recipe/service/ChoiceRecipeService.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
Labels: 기능 추가, 기능 수정

#95 🔀 :: (#93) 매일 식단 알람 보내는 Scheduler 작성
  src/main/java/com/meturial/MeturialBackendApplication.java
  src/main/java/com/meturial/domain/menu/domain/repository/CustomMenuRepository.java
  src/main/java/com/meturial/domain/menu/domain/repository/CustomMenuRepositoryImpl.java
  src/main/java/com/meturial/domain/user/domain/repository/CustomUserRepository.java
  src/main/java/com/meturial/domain/user/domain/repository/CustomUserRepositoryImpl.java
  src/main/java/com/meturial/domain/user/domain/repository/UserRepository.java
  src/main/java/com/meturial/global/scheduler/SendMenuNotificationScheduler.java
  src/main/java/com/meturial/infra/fcm/FcmService.java
Labels: 기능 추가

#96 🔀 :: (#94) 레시피 상세 조회 500 해결
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/domain/repository/vo/QueryRecipeDetailVo.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/CategoryElement.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/QueryRecipeDetailResponse.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/RecipeSequenceElement.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
  src/main/java/com/meturial/domain/review/domain/repository/CustomReviewRepository.java
  src/main/java/com/meturial/domain/review/domain/repository/CustomReviewRepositoryImpl.java
Labels: 버그

#98 🔀 :: (#97) 인기 레시피 랭킹 조회 500 해결
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/domain/repository/RecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/vo/QueryRecipeReviewVo.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
Labels: 버그

#102 🔀 :: (#101) 찜 여부 확인 응답 추가
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/QueryRecipeDetailResponse.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/QueryRecipeStarRatingCountResponse.java
  src/main/java/com/meturial/domain/recipe/presentation/dto/response/RecipeRankingElement.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
  src/main/java/com/meturial/domain/review/domain/repository/ReviewRepository.java
Labels: 기능 수정

#106 🔀 :: (#105) 인기 레시피 랭킹 조회 500 해결
  src/main/java/com/meturial/domain/recipe/domain/ChoiceRecipe.java
  src/main/java/com/meturial/domain/recipe/domain/repository/ChoiceRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
Labels: 버그

#104 🔀 :: (#103) 찜 레시피 목록 조회에서 평점 Null 응답 해결
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomChoiceRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/domain/repository/CustomChoiceRecipeRepositoryImpl.java
  src/main/java/com/meturial/domain/recipe/service/ChoiceRecipeService.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
Labels: 버그

#108 🔀 :: (#107) 전체적인 코드 리팩토링
  src/main/java/com/meturial/domain/auth/service/AuthService.java
  src/main/java/com/meturial/domain/menu/facade/MenuFacade.java
  src/main/java/com/meturial/domain/menu/presentation/dto/response/MenuDetailElement.java
  src/main/java/com/meturial/domain/menu/presentation/dto/response/MenuNotificationElement.java
  src/main/java/com/meturial/domain/menu/service/MenuService.java
  src/main/java/com/meturial/domain/notification/presentation/dto/response/NotificationSettingElement.java
  src/main/java/com/meturial/domain/notification/service/NotificationService.java
  src/main/java/com/meturial/domain/recipe/facade/ChoiceRecipeFacade.java
  src/main/java/com/meturial/domain/recipe/facade/RecipeFacade.java
  src/main/java/com/meturial/domain/recipe/service/ChoiceRecipeService.java
  src/main/java/com/meturial/domain/recipe/service/RecipeService.java
  src/main/java/com/meturial/domain/review/facade/ReviewFacade.java
  src/main/java/com/meturial/domain/review/presentation/dto/response/MyReviewElement.java
  src/main/java/com/meturial/domain/review/presentation/dto/response/ReviewElement.java
  src/main/java/com/meturial/domain/review/service/ReviewService.java
  src/main/java/com/meturial/domain/user/domain/User.java
  src/main/java/com/meturial/domain/user/presentation/UserController.java
  src/main/java/com/meturial/domain/user/service/UserService.java
  src/main/java/com/meturial/global/entity/BaseUUIDEntity.java
  src/main/java/com/meturial/global/error/ErrorResponse.java
  src/main/java/com/meturial/global/error/ExceptionFilter.java
  src/main/java/com/meturial/global/error/GlobalExceptionHandler.java
  src/main/java/com/meturial/global/property/PropertyConfig.java
  src/main/java/com/meturial/global/security/jwt/JwtTokenFilter.java
  src/main/java/com/meturial/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/meturial/infra/s3/S3Facade.java
Labels: 구조 변경

#110 🔀 :: (#109) RecipeId로 찜 삭제하도록 수정
  src/main/java/com/meturial/domain/recipe/domain/repository/ChoiceRecipeRepository.java
  src/main/java/com/meturial/domain/recipe/presentation/ChoiceRecipeController.java
  src/main/java/com/meturial/domain/recipe/service/ChoiceRecipeService.java
Labels: 기능 수정
